### ISSUE TITLE
Unexpected end of JSON input when source map is empty

### ISSUE THREAD

**Issue by Shpingalet007** [clean-css/clean-css#1194]
### Environment

* clean-css version: 4.2.3 - 5.2.2
* node.js version: 14 - 17
* operating system: Mac OS Big Sur 11.6.2
* plugin: gulp-clean-css

### Configuration options

```js
const cleanCss = require('gulp-clean-css');

/** gulp-clean-css configs are empty... **/

gulp
  .src(source)
  .pipe(sourcemaps.init())
  .pipe(lessCompiler())
  .pipe(sourcemaps.write('.'))
  .pipe(cleanCss())
```
```js
const CleanCSS = require('clean-css');

/**
 * ...what means that clean-css configs
 * are empty too, and are identical to
 * the next code
 */

new CleanCSS({});
```

### Input CSS
Any css and an empty css.map files

### Actual output CSS
Any css and an empty css.map files

### Expected behavior
No error produced or better description provided
```
[00:00:00] SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at loadInputSourceMapFromLocalUri (/my-module/node_modules/gulp-clean-css/node_modules/clean-css/lib/reader/apply-source-maps.js:177:15)
    at extractInputSourceMapFrom (/my-module/node_modules/gulp-clean-css/node_modules/clean-css/lib/reader/apply-source-maps.js:116:17)
    at fetchAndApplySourceMap (/my-module/node_modules/gulp-clean-css/node_modules/clean-css/lib/reader/apply-source-maps.js:79:10)
    at doApplySourceMaps (/my-module/node_modules/gulp-clean-css/node_modules/clean-css/lib/reader/apply-source-maps.js:57:14)
    at applySourceMaps (/my-module/node_modules/gulp-clean-css/node_modules/clean-css/lib/reader/apply-source-maps.js:33:5)
    at Object.callback (/my-module/node_modules/gulp-clean-css/node_modules/clean-css/lib/reader/read-sources.js:25:12)
    at doInlineImports (/my-module/node_modules/gulp-clean-css/node_modules/clean-css/lib/reader/read-sources.js:200:25)
    at Object.callback (/my-module/node_modules/gulp-clean-css/node_modules/clean-css/lib/reader/read-sources.js:324:14)
    at doInlineImports (/my-module/node_modules/gulp-clean-css/node_modules/clean-css/lib/reader/read-sources.js:200:25)
```

**Comment by Shpingalet007** [comment]
Flag `sourcemaps: false` solves the problem, but in this case we omit mappings.

**Comment by jakubpawlowicz** [comment]
It's out in clean-css 5.2.3. Thanks for contribution!
